### ISSUE TITLE
Can't run `devtools::check()` in codespace setup with apt-packages and r-packages features

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [rocker-org/devcontainer-features#156]
We're using the r-packages feature [here](https://github.com/NOAA-FIMS/FIMS/blob/e1b5631be58e275452c8b299e4680e662d238233/.devcontainer/devcontainer.json#L15)

I verified the packages installed with that feature work, but if I open the R terminal and run `devtools::check()` I receive the following error:

cannot open URL 'https://packagemanager.posit.co/cran/__linux__/jammy/latest/web/packages/packages.rds': HTTP status was '404 Not Found'

I appreciate any input you can provide on this error. Thanks!

**Comment by eitsupi** [comment]
Hi, thank you sharing your use case.

This error has nothing to do with Dev Container Features, it is a base image issue.
In other words, it is a duplication of rocker-org/rocker-versioned2#532.

The solution is to use the `options` funciton to change the CRAN url.
Like this:

```r
options(repos = c(CRAN = "https://cloud.r-project.org"))
devtools::check()
```

Perhaps we need to document this.
