### ISSUE TITLE
[r-apt][r-rig] Consider using pipx to install radian

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/devcontainer-features#162]
It seems that radian installation fails on the latest version of Debian.

```log
[2023-05-12T14:35:24.662Z] #18 84.83 error: externally-managed-environment
#18 84.83 
#18 84.83 × This environment is externally managed
#18 84.83 ╰─> To install Python packages system-wide, try apt install
#18 84.83     python3-xyz, where xyz is the package you are trying to
#18 84.83     install.
#18 84.83     
#18 84.83     If you wish to install a non-Debian-packaged Python package,
#18 84.83     create a virtual environment using python3 -m venv path/to/venv.
#18 84.83     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
#18 84.83     sure you have python3-full installed.

[2023-05-12T14:35:24.662Z] #18 84.83     
#18 84.83     If you wish to install a non-Debian packaged Python application,
#18 84.83     it may be easiest to use pipx install xyz, which will manage a
#18 84.83     virtual environment for you. Make sure you have pipx installed.
#18 84.83     
#18 84.83     See /usr/share/doc/python3.11/README.venv for more information.
#18 84.83 
#18 84.83 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
#18 84.83 hint: See PEP 668 for the detailed specification.
#18 84.90 ERROR: Feature "./r-apt" (Unknown) failed to install! Look at the documentation at https://github.com/rocker-org/devcontainer-features/tree/main/src/r-apt for help troubleshooting this error.
```

https://github.com/rocker-org/devcontainer-features/actions/runs/4960009387/jobs/8874893451#step:4:2540

Perhaps it would be easiest here to install radian via pipx?

Concerns about installing radian via pipx:

- Configuring both root and non-root users to have access to the same tools is quite complicated and I don't want to do it here.
- Does it work well when using `raticulate` in radian?

**Comment by ChristineStawitz-NOAA** [comment]
Right now we are unable to open an R terminal in our codespace while using 	`"image": "ghcr.io/rocker-org/devcontainer/r-ver:4.2",` and I think it could be due to this issue. Do you have a workaround, or would it be possible to switch the R terminal to the default and not radian until the radian install issue is fixed?

Thanks!!

**Comment by eitsupi** [comment]
@ChristineStawitz-NOAA
> Right now we are unable to open an R terminal in our codespace while using `"image": "ghcr.io/rocker-org/devcontainer/r-ver:4.2",` and I think it could be due to this issue. Do you have a workaround, or would it be possible to switch the R terminal to the default and not radian until the radian install issue is fixed?

I don't think this is related to this. Please open a new issue to the base image's repo and provide more info.
(I can't guess what "unable to open an R terminal" mean)

**Comment by eitsupi** [comment]
@ChristineStawitz-NOAA I created a Codespace on https://github.com/eitsupi/prqlr and was able to reproduce that.
This is due to the fact that the VSCode extension is not loaded when Codespaces start, and it has nothing to do with this Feature or vscode-R (please check that JS Debugger does not work as well).

In other words, it is a Codespaces issue.
The workaround is to reload the window from the command palette.

**Comment by ChristineStawitz-NOAA** [comment]
Thanks for the update, I was able to fix it by reloading the window.
