### ISSUE TITLE
[miniforge] install should not fail if conda/mamba are already present

### ISSUE THREAD

**Issue by rokroskar** [rocker-org/devcontainer-features#166]
The install fails here if conda/mamba are already installed: https://github.com/rocker-org/devcontainer-features/blob/54829966edca06bd81e58a38ad28b57a993fd6e5/src/miniforge/install.sh#L15

The exit code should be `0` so as to not break a devcontainer build in case a base image is used which already contains conda/mamba.

**Comment by eitsupi** [comment]
Thanks for pointing that!
Could you make a PR to fix this?

**Comment by rokroskar** [comment]
I wasn't sure if this was done intentionally, but it sounds like it was not in which case I'm happy to send a PR.

**Comment by eitsupi** [comment]
> I wasn't sure if this was done intentionally, but it sounds like it was not in which case I'm happy to send a PR.

Yes, I think the changes you suggest make sense, and I would be willing to review and merge that if you send a PR.
