### ISSUE TITLE
rstudio-server: Ubuntu 24.04 (noble) not yet supported

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [rocker-org/devcontainer-features#232]
Redacted output:
<pre>
Downloading RStudio Server...
/tmp/rstudio-server /tmp/dev-container-features/rstudio-server_1
Download from https://rstudio.org/download/latest/stable/server/noble/rstudio-server-latest-amd64.deb
(!) Version stable for noble amd64 is not found
</pre>

**Comment by eitsupi** [comment]
My understanding is that this is an upstream issue and that 24.04 is not actually supported.

**Comment by HenningLorenzen-ext-bayer** [comment]
> My understanding is that this is an upstream issue and that 24.04 is not actually supported.

😞

**Comment by HenningLorenzen-ext-bayer** [comment]
I have been digging into this lately, my understanding is now the following:

1. RStudio *Desktop* has some serious issues related to the Electron runtime used for Desktop.
2. RStudio *Server* builds for Ubuntu 22.04 may work 'off-label'. I have been able to run [RStudio Server 2024.04.2+764](https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2024.04.2-764-amd64.deb) on Ubuntu 24.04.

Maybe Posit will never release an RStudio Server 2024.04.x build specifically for Ubuntu 24.04.

**Comment by eitsupi** [comment]
The latest release of RStudio solve this.

**Comment by eitsupi** [comment]
RStudio does not publish download URLs for noble, but reuses the URLs for jammy, so this needs to be corrected.
