### ISSUE TITLE
New feature: RStudio Server

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/devcontainer-features#71]
There may be demand to use RStudio Server in combination with r-apt feature or r-rig feature.

**Comment by eitsupi** [comment]
Thank you for your interest in this! I am not currently working on this.

I don't think there are any blockers against simply installing RStudio Server, but I think RStudio has some differences from existing Features, such as the requirement to run as root and the fact that it is an IDE, making it difficult to test with the Dev Container CLI's test command.

If you are willing to work on this, I would be happy to review it.

**Comment by eitsupi** [comment]
Thanks, I have to admit that I do not sufficiently understand RStudio Server. (@cboettig definitely has more experience and knowledge than I do)

Since https://github.com/rocker-org/rocker-versioned2/blob/e80ff87cb06d6de5e1b8333f184feed2196ab8c4/scripts/install_rstudio.sh is intended to run RStudio Server via s6-overlay, I believe it may be slightly different than here.

In any case, if we can write a more generic install script here than `install_rstudio.sh`, it would be great.
Also, `install_rstudio.sh` takes into account the possibility of multiple users on the container, which is probably not necessary with Dev Container.

**Comment by rokroskar** [comment]
Thanks, that makes sense. Regarding the RStudio installation scripts - what are the limitations wrt arm? I have only been able to get it to work with some specific RStudio versions and only on Ubuntu jammy.

**Comment by rokroskar** [comment]
Also, I'm not sure I understand what you mean by "more generic"? What are the specific assumptions it makes that you feel shouldn't apply here?

**Comment by cboettig** [comment]
just a note that you can already run rstudio in codespaces in the 'usual ways', I think it's a just a design question of approach is most streamlined and user-friendly.  

e.g. the existing rocker devcontainers based on versioned2 stack have rstudio installed, and it can be launched manually from the terminal at any time (`sudo rsudio-server start`) or configured to run automatically at launch in the devcontainer: https://github.com/espm-157/devcontainers-rstudio/blob/main/.devcontainer/devcontainer.json

Users have taken other routes too, e.g. https://www.youtube.com/watch?v=bzvDaQTqgLg from some NOAA researchers.  (not that I'd recommend this approach, but maybe highlights the need for us to document a more intuitive built-in). 

I agree with @eitsupi that having s6-overlay running with multiple users etc also feels overkill for this situation, and a lighter single-user install probably makes sense.  Luckily codespaces are fine with having sudo enabled, so this case is relatively straight-forward I think.

**Comment by rokroskar** [comment]
Hi @cboettig

> just a note that you can already run rstudio in codespaces in the 'usual ways', I think it's a just a design question of approach is most streamlined and user-friendly.

by "the usual ways" you mean by running one of the rocker images? 

> e.g. the existing rocker devcontainers based on versioned2 stack have rstudio installed, and it can be launched manually from the terminal at any time (`sudo rsudio-server start`) or configured to run automatically at launch in the devcontainer: https://github.com/espm-157/devcontainers-rstudio/blob/main/.devcontainer/devcontainer.json

Sure, that's true - my interest is in supporting mechanisms for users to compose their own images for whatever they need. The focus for us is not codespaces specifically. 

> I agree with @eitsupi that having s6-overlay running with multiple users etc also feels overkill for this situation, and a lighter single-user install probably makes sense. Luckily codespaces are fine with having sudo enabled, so this case is relatively straight-forward I think.

I think I must be missing something here - why is sudo required? We've been basing our builds off the rocker stack for years and have been running rstudio without sudo. Is there some nuance we are ignoring?

I'm wondering though if given the complexity of rstudio it wouldn't be better to recommend to users of devcontainers to base their projects off one of the rocker images and add whatever else they need to that instead of the other way around. tbh I see benefits and drawbacks of both approaches. If we could make the rstudio install script generic enough to conform as much as possible to what already exists in the image at the time that it's being installed (e.g. any existing user setup), I think that would be great. otoh installing R and all the "basic" packages that people want takes a really long time because it often has to compile things, so pulling an image just seems easier.

**Comment by eitsupi** [comment]
Thinking about it again, sudo is certainly unnecessary. For example, in the Rocker Project image, `rocker/binder` starts RStudio Server without using sudo.

> Also, I'm not sure I understand what you mean by "more generic"? What are the specific assumptions it makes that you feel shouldn't apply here?

It was meant to be a Dev Container Feature to install RStudio Server on a generic Ubuntu-based or Debian-based images.

For example, as a known limitation, the `install_rstudio.sh` script does not seem to be able to run on `rocker/r2u` (`ubuntu` base image).

**Comment by rokroskar** [comment]
Do you know a good place where it's documented how to download rstudio? I was only able to get the URL to work for some specific version (on my M1 mac) and wasn't able to find good docs on that.

**Comment by eitsupi** [comment]
> Do you know a good place where it's documented how to download rstudio? I was only able to get the URL to work for some specific version (on my M1 mac) and wasn't able to find good docs on that.

I believe all the links are listed on this site.
<https://dailies.rstudio.com/>

This section on URL patterns may also be helpful.
https://github.com/rocker-org/rocker-versioned2/blob/e80ff87cb06d6de5e1b8333f184feed2196ab8c4/scripts/install_rstudio.sh#L61-L69

**Comment by rokroskar** [comment]
Are arm builds only available as dailies? I can't find them where they [list the stable builds](https://posit.co/download/rstudio-server/). I guess that would explain why I couldn't find them :)

**Comment by eitsupi** [comment]
> Are arm builds only available as dailies? I can't find them where they [list the stable builds](https://posit.co/download/rstudio-server/). I guess that would explain why I couldn't download them :)

Yeah, see this issue. rstudio/rstudio#13340
