### ISSUE TITLE
TinyTex not found, even though it has been installed

### ISSUE THREAD

**Issue by edxu96** [rocker-org/devcontainer-features#75]
Thanks for the effort. It's hard to install Quarto with this Feature.

However, it seems TinyTex cannot be found by Quarto:

```plain
No TeX installation was detected.

Please run 'quarto install tinytex' to install TinyTex.
If you prefer, you may install TexLive or another TeX distribution.
```

But it has been installed by this Feature:

```
$ quarto install tool tinytex
tinytex is already installed and up to date.
```

Here is the `devcontainer.json` I used:

```json
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		"context": "..",
		"args": { "VARIANT": "ubuntu-22.04" }
	},

	"postCreateCommand": "pip3 install -r dev-requirements.txt",

	"features": {
                "ghcr.io/rocker-org/devcontainer-features/quarto-cli:1": {
            		"version": "prerelease",
            		"installTinyTex": true
        	},
		"ghcr.io/devcontainers/features/python:1": {
			"version": "3.9",
			"installTools": false,
			"installJupyterlab": false
		}
	},

	"remoteUser": "vscode",

	"customizations": {
		"vscode": {
			"extensions": [
				"bungcip.better-toml",
				"streetsidesoftware.code-spell-checker"
			]
		}
	},

	"containerEnv": {
		"QUARTO_PYTHON": "/usr/local/python/current/bin/python3"
	}
}
```

**Comment by eitsupi** [comment]
Hi, thank you for using this feature!

What operation does that error message appear for?
The result was unexpected for me, since this feature tests that it can render pdf format as follows

https://github.com/rocker-org/devcontainer-features/blob/57a85fad144e2ad7c057ce5e9c2527ef08802bb9/test/quarto-cli/tinytex.sh#L8-L19

**Comment by eitsupi** [comment]
TinyTex is installed in the user directory.
Therefore, if the root user executes the `quarto render` command on that image (the image where the non-root user exists), TinyTex will not be recognized.

I just tried it and it seems to work in my environment.

```json
{
	"image": "mcr.microsoft.com/devcontainers/python:3",
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/quarto-cli:latest": {
			"version": "prerelease",
			"installTinyTex": true
		}
	},
	"remoteUser": "vscode",
	"postCreateCommand": "python3 -m pip install jupyter"
}
```

```qmd
---
title: Test
format:
    pdf: default
---

Hello Quarto!
```

![image](https://user-images.githubusercontent.com/50911393/196654432-692defb7-87a7-4684-b17c-1992969ef260.png)

**Comment by edxu96** [comment]
Thanks for the quick reply.

> What operation does that error message appear for?

```
quarto render test.qmd
```

and `test.qmd` is set to produce a PDF.

---

I will try the Json you provided.

**Comment by eitsupi** [comment]
I'm glad to hear that!
